#!/usr/bin/env python3
import numpy as np
import os
import time

INPUT_FILE = "rank_distribution.txt"
OUTPUT_FILE = "../include/phevaluator/strength_lut.h"
THEORETICAL_TOTAL_HANDS = 133784560  # C(52, 7)
MAX_WAIT_SECONDS = 600  # 10分钟超时
def create_lut():
    print(f"Waiting for {INPUT_FILE} to be generated...")
    start_time = time.time()
    while not os.path.exists(INPUT_FILE):
        if time.time() - start_time > MAX_WAIT_SECONDS:
            print(f"Error: {INPUT_FILE} not found after {MAX_WAIT_SECONDS} seconds")
            return
        time.sleep(5)

    print(f"Found {INPUT_FILE}, processing...")

    # Read the distribution data
    # Rank is 1-based, so we use an array of size 7463
    rank_counts = np.zeros(7463, dtype=np.int64)
    with open(INPUT_FILE, 'r') as f:
        for line in f:
            if line.strip().startswith('#') or not line.strip():
                continue
            try:
                rank, count = map(int, line.strip().split(','))
                if 1 <= rank <= 7462:
                    rank_counts[rank] = count
            except ValueError:
                print(f"Warning: Skipping malformed line: {line.strip()}")
                continue

    # Dynamically calculate the total number of hands from the file
    actual_total_hands = np.sum(rank_counts)
    print(f"Actual total hands from file: {actual_total_hands}")
    if actual_total_hands == 0:
        print("Error: No hands found in distribution file. Aborting.")
        return

    if actual_total_hands != THEORETICAL_TOTAL_HANDS:
        print(f"Warning: Actual hand count ({actual_total_hands}) does not match theoretical count ({THEORETICAL_TOTAL_HANDS}).")
        print("Proceeding with actual count...")

    cumulative_counts = np.cumsum(rank_counts)

    # The maximum number of hands a single hand can beat is the total number of hands
    # minus the number of hands in the best rank (rank 1).
    max_beaten = actual_total_hands - rank_counts[1]
    if max_beaten <= 0:
        print("Error: max_beaten is zero or negative. Cannot scale properly.")
        return

    cumulative_counts = np.zeros(7463, dtype=np.int64)
    cumulative_counts[1] = rank_counts[1]
    for rank in range(2, 7463):
        cumulative_counts[rank] = cumulative_counts[rank-1] + rank_counts[rank]

    # 计算最大可击败手牌数（包含平局处理）
    max_beaten = actual_total_hands - rank_counts[1]  # 最好排名只能击败其他所有牌

    # 创建强度查找表 - 修改为10000上限
    strength_lut = np.zeros(7463, dtype=np.uint32)

    for rank in range(1, 7463):
        # 严格更差的手牌数量
        worse_hands = actual_total_hands - cumulative_counts[rank]

        # 当前排名的手牌数量（用于平局计算）
        tie_hands = rank_counts[rank] - 1  # 排除自己

        # 等效击败手牌数 = 严格击败 + 50%平局
        equivalent_beaten = worse_hands + tie_hands // 2

        # 使用10000作为上限，简化数值范围
        strength = (equivalent_beaten * 10000 + max_beaten//2) // max_beaten
        strength_lut[rank] = min(strength, 10000)  # 确保不超过10000上限

    # Write to a C header file
    print(f"Writing strength lookup table to {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, 'w') as f:
        f.write("/*\n")
        f.write(" * Hand Strength Lookup Table\n")
        f.write(" * Automatically generated by create_strength_lut.py\n")
        f.write(f" * Based on a total of {actual_total_hands} unique 7-card hands.\n")
        f.write(" * Maps hand rank (1-7462) to a strength score (0-10,000)\n")
        f.write(" */\n\n")
        f.write("#ifndef STRENGTH_LUT_H\n")
        f.write("#define STRENGTH_LUT_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("static const uint32_t hand_strength_lut[7463] = {\n")
        f.write("    0, // Index 0 is unused, ranks are 1-based\n")

        for i in range(1, 7463):
            f.write(f"    {strength_lut[i]}")
            if i < 7462:
                f.write(",")
            if i % 10 == 0:
                f.write("\n")

        f.write("\n};\n\n")
        f.write("#endif // STRENGTH_LUT_H\n")

    print(f"Done. New LUT generated with max strength: {strength_lut[1]}")

if __name__ == "__main__":
    create_lut()