/*
 * Lookup Table Generator for Texas Hold'em Potential Evaluator
 * This program generates static lookup tables at compile time to eliminate
 * runtime initialization overhead.
 *
 * Generated file: evaluator_holdem_potential_tables.h
 */

#include <stdio.h>
#include <stdlib.h>
// #include <math.h>
#include "../include/phevaluator/phevaluator.h"
#include "../include/phevaluator/evaluator_holdem_potential.h" // Ensure this is included to get declarations

// Constants (must match evaluator_holdem_potential.c)
#define FLUSH_DRAW_WEIGHT 200
#define STRAIGHT_DRAW_WEIGHT 150
#define SET_POTENTIAL_WEIGHT 100
#define OVERCARDS_WEIGHT 50

// Function prototypes for table generation
void generate_flush_potential_lut(FILE* fp);
void generate_straight_potential_lut(FILE* fp);
void generate_set_potential_lut(FILE* fp);
void generate_overcards_lut(FILE* fp);

int main(int argc, char** argv) {
    const char* output_file = "evaluator_holdem_potential_tables.h";

    if (argc > 1) {
        output_file = argv[1];
    }

    printf("Generating lookup tables to %s...\n", output_file);

    FILE* fp = fopen(output_file, "w");
    if (!fp) {
        fprintf(stderr, "Error: Cannot create output file %s\n", output_file);
        return 1;
    }

    // Write header
    fprintf(fp, "/*\n");
    fprintf(fp, " * Auto-generated lookup tables for Texas Hold'em Potential Evaluator\n");
    fprintf(fp, " * Generated by generate_potential_tables.c\n");
    fprintf(fp, " * DO NOT EDIT THIS FILE MANUALLY\n");
    fprintf(fp, " */\n\n");

    fprintf(fp, "#ifndef EVALUATOR_HOLDEM_POTENTIAL_TABLES_H\n");
    fprintf(fp, "#define EVALUATOR_HOLDEM_POTENTIAL_TABLES_H\n\n");

    // Generate all lookup tables
    generate_flush_potential_lut(fp);
    generate_straight_potential_lut(fp);
    generate_set_potential_lut(fp);
    generate_overcards_lut(fp);

    fprintf(fp, "#endif // EVALUATOR_HOLDEM_POTENTIAL_TABLES_H\n");

    fclose(fp);

    printf("Successfully generated lookup tables!\n");
    printf("Memory usage:\n");
    printf("  - Flush potential LUT: %zu bytes\n", 65536 * sizeof(int));
    printf("  - Straight potential LUT: %zu bytes\n", 8192 * sizeof(int));
    printf("  - Set potential LUT: %zu bytes\n", 13 * 8192 * 6 * sizeof(int));
    printf("  - Overcards LUT: %zu bytes\n", 13 * 13 * 13 * sizeof(int));
    printf("  - Total: %zu bytes (%.2f MB)\n",
           65536 * sizeof(int) + 8192 * sizeof(int) + 13 * 8192 * 6 * sizeof(int) + 13 * 13 * 13 * sizeof(int),
           (65536 * sizeof(int) + 8192 * sizeof(int) + 13 * 8192 * 6 * sizeof(int) + 13 * 13 * 13 * sizeof(int)) / 1024.0 / 1024.0);

    return 0;
}

void generate_flush_potential_lut(FILE* fp) {
    printf("Generating flush potential lookup table (using new probability logic)...\n");

    fprintf(fp, "// Flush potential lookup table: [suit_pattern] -> potential_value\n");
    fprintf(fp, "// suit_pattern encodes the count of each suit as a 16-bit value: 4 bits per suit\n");
    fprintf(fp, "static const int flush_potential_lut[65536] = {\n");

    int dummy_cards[7]; // Max 7 cards

    for (int pattern = 0; pattern < 65536; pattern++) {
        int suits[4] = {
            (pattern >> 0) & 0xF,
            (pattern >> 4) & 0xF,
            (pattern >> 8) & 0xF,
            (pattern >> 12) & 0xF
        };

        int card_count = 0;
        for(int s_idx=0; s_idx<4; ++s_idx) card_count += suits[s_idx];

        int current_dummy_idx = 0;
        if (card_count > 0 && card_count <= 7) {
            for (int s_idx = 0; s_idx < 4; ++s_idx) {
                for (int c = 0; c < suits[s_idx]; ++c) {
                    if (current_dummy_idx < card_count) {
                        // Assign a unique rank for each card to avoid issues with other potential calcs if they were used
                        // For flush potential, only suit matters. Rank is (current_dummy_idx << 2)
                        dummy_cards[current_dummy_idx] = (current_dummy_idx << 2) | s_idx;
                        current_dummy_idx++;
                    }
                }
            }
        } else if (card_count > 7) { // Invalid pattern, more than 7 cards specified by suit counts
             card_count = 0; // Treat as no potential
        }

        int potential = 0;
        if (card_count >= 2 && card_count <= 7) { // Need at least 2 cards for any potential
             potential = calculate_flush_potential(dummy_cards, card_count);
        }

        fprintf(fp, "%d", potential);
        if (pattern < 65535) fprintf(fp, ",");
        if (pattern % 16 == 15) fprintf(fp, "\n");
    }

    fprintf(fp, "};\n\n");
}

void generate_straight_potential_lut(FILE* fp) {
    printf("Generating straight potential lookup table (using new probability logic, assuming flop stage)...\n");

    fprintf(fp, "// Straight potential lookup table: [rank_pattern] -> potential_value\n");
    fprintf(fp, "// rank_pattern encodes which ranks are present as a 13-bit mask\n");
    fprintf(fp, "// Assumes card_count = 5 (flop) for probability calculations.\n");
    fprintf(fp, "static const int straight_potential_lut[8192] = {\n");

    int assumed_card_count_for_lut = 5; // For flop stage

    for (int pattern = 0; pattern < 8192; pattern++) { // pattern is the rank_mask
        int potential = 0;
        int num_total_outs = get_straight_outs_count(pattern, assumed_card_count_for_lut);

        if (num_total_outs > 0) {
            double probability = get_card_draw_probability(num_total_outs, assumed_card_count_for_lut);

            if (num_total_outs == 8) {
                potential = (int)(probability * STRAIGHT_DRAW_WEIGHT);
            } else {
                potential = (int)(probability * STRAIGHT_DRAW_WEIGHT * (double)num_total_outs / 8.0);
            }
        }

        fprintf(fp, "%d", potential);
        if (pattern < 8191) fprintf(fp, ",");
        if (pattern % 16 == 15) fprintf(fp, "\n");
    }

    fprintf(fp, "};\n\n");
}

void generate_set_potential_lut(FILE* fp) {
    printf("Generating set potential lookup table...\n");

    fprintf(fp, "// Set potential lookup table: [pair_rank][board_mask][remaining_cards] -> potential_value\n");
    fprintf(fp, "static const int set_potential_lut[13][8192][6] = {\n");

    for (int pair_rank = 0; pair_rank < 13; pair_rank++) {
        fprintf(fp, "  { // pair_rank = %d\n", pair_rank);

        for (int board_mask = 0; board_mask < 8192; board_mask++) {
            fprintf(fp, "    {");

            for (int remaining = 0; remaining < 6; remaining++) {
                int potential;

                // Check if pair rank appears on board (already made set)
                if (board_mask & (1 << pair_rank)) {
                    potential = 0;
                } else {
                    // Award potential based on remaining cards
                    potential = (SET_POTENTIAL_WEIGHT * remaining) / 5;
                }

                fprintf(fp, "%d", potential);
                if (remaining < 5) fprintf(fp, ",");
            }

            fprintf(fp, "}");
            if (board_mask < 8191) fprintf(fp, ",");
            if (board_mask % 8 == 7) fprintf(fp, "\n");
        }

        fprintf(fp, "  }");
        if (pair_rank < 12) fprintf(fp, ",");
        fprintf(fp, "\n");
    }

    fprintf(fp, "};\n\n");
}

void generate_overcards_lut(FILE* fp) {
    printf("Generating overcards lookup table...\n");

    fprintf(fp, "// Overcards lookup table: [hole_pattern][board_high] -> potential_value\n");
    fprintf(fp, "// hole_pattern: encodes the two hole card ranks, board_high: 0-12\n");
    fprintf(fp, "static const int overcards_lut[169][13] = {\n");

    for (int hole_pattern = 0; hole_pattern < 13*13; hole_pattern++) {
        int rank1 = hole_pattern / 13;
        int rank2 = hole_pattern % 13;

        fprintf(fp, "  {");

        for (int board_high = 0; board_high < 13; board_high++) {
            int overcard_count = 0;
            if (rank1 > board_high) overcard_count++;
            if (rank2 > board_high) overcard_count++;

            int potential = overcard_count * OVERCARDS_WEIGHT;

            fprintf(fp, "%d", potential);
            if (board_high < 12) fprintf(fp, ",");
        }

        fprintf(fp, "}");
        if (hole_pattern < 168) fprintf(fp, ",");
        fprintf(fp, "\n");
    }

    fprintf(fp, "};\n\n");
}